[build.env]
passthrough = [
    "BUILD_SOURCEVERSION",
    "VERSION",
]

[target.armv7-unknown-linux-gnueabihf]
image = "azureiotedge_crossbuilder:gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf"

[target.aarch64-unknown-linux-gnu]
image = "azureiotedge_crossbuilder:gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu"
